spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: 
    password: 
    url: 
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    context-path: 
  port: 



applet:
   loginUrl: 
   appid: 
   secret: 
   grant_type: 

pc:
   appid: 
   secret: 
   grant_type: 
   accessTokenUrl: 
   userInfoUrl: 

picAddr: 


