spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: bcxzs
    password: bcxzs!$123
    url: jdbc:mysql://39.108.147.128:6300/bcxzs?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    context-path: /bcxzs
  port: 8090



applet:
   loginUrl: https://api.weixin.qq.com/sns/jscode2session
   appid: wx4a7829f2688c8ce8
   secret: c3a4b7c58663039e6691687bbf192bf0
   grant_type: authorization_code

pc:
   appid: wx4c324b41355a11b0
   secret: ea19e67f6ee8df317a74b910c0f0ff44
   grant_type: authorization_code
   accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
   userInfoUrl: https://api.weixin.qq.com/sns/userinfo

picAddr: http://pfll08m1b.bkt.clouddn.com/


